config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users
  get 'population_dynamics/home'

  get 'population_dynamics/charts'

  resources :relations
  resources :countries
  resources :indicators
  
  root 'population_dynamics#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relation.rb
class Relation < ApplicationRecord
    validates :countrycode, :indicatorcode, presence: true
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = if params[:term]
        Relation.where("LOWER(countrycode) LIKE ? OR LOWER(indicatorcode) LIKE ?", "%#{params[:term].downcase}%", "%#{params[:term].downcase}%")
      else
        Relation.all
    end
    @countries = Country.all
    @indicators = Indicator.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
    @countries = Country.all
    @indicators = Indicator.all
  end

  # GET /relations/new
  def new
    @relation = Relation.new
    @countries = Country.all
    @indicators = Indicator.all
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relations_url, notice: 'Relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:countrycode, :indicatorcode, :y2007, :y2008, :y2009, :y2010, :y2011, :y2012, :y2013, :y2014, :y2015, :y2016, :term)
    end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.erb
<%= form_with(model: relation, local: true) do |form| %>
  <% if relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Country<br><%= form.collection_select( :countrycode, @countries, :id, :name ) %>
  </div>

  <div class="field">
    Indicator<br><%= form.collection_select( :indicatorcode, @indicators, :id, :name ) %>
  </div>

  <div class="field">
    <%= form.label :y2007 %>
    <%= form.number_field :y2007, id: :relation_y2007 %>
  </div>

  <div class="field">
    <%= form.label :y2008 %>
    <%= form.number_field :y2008, id: :relation_y2008 %>
  </div>

  <div class="field">
    <%= form.label :y2009 %>
    <%= form.number_field :y2009, id: :relation_y2009 %>
  </div>

  <div class="field">
    <%= form.label :y2010 %>
    <%= form.number_field :y2010, id: :relation_y2010 %>
  </div>

  <div class="field">
    <%= form.label :y2011 %>
    <%= form.number_field :y2011, id: :relation_y2011 %>
  </div>

  <div class="field">
    <%= form.label :y2012 %>
    <%= form.number_field :y2012, id: :relation_y2012 %>
  </div>

  <div class="field">
    <%= form.label :y2013 %>
    <%= form.number_field :y2013, id: :relation_y2013 %>
  </div>

  <div class="field">
    <%= form.label :y2014 %>
    <%= form.number_field :y2014, id: :relation_y2014 %>
  </div>

  <div class="field">
    <%= form.label :y2015 %>
    <%= form.number_field :y2015, id: :relation_y2015 %>
  </div>

  <div class="field">
    <%= form.label :y2016 %>
    <%= form.number_field :y2016, id: :relation_y2016 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relations</h1>

<p>
  <i>Search relations by country or indicator's code</i><br>
  <%= form_tag(relations_path, method: :get) do %>
  <%= text_field_tag :term %>
  <%= submit_tag 'Search' %>
<% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Indicator</th>
      <th>2007</th>
      <th>2008</th>
      <th>2009</th>
      <th>2010</th>
      <th>2011</th>
      <th>2012</th>
      <th>2013</th>
      <th>2014</th>
      <th>2015</th>
      <th>2016</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <% @countries.each do |country| %>
          <% if relation.countrycode == country.code %>
            <td><%= country.name %> <i><%= country.code %></i></td>
          <% end %>
        <% end %>
        <% @indicators.each do |indicator| %>
          <% if relation.indicatorcode == indicator.code %>
            <td><%= indicator.name %> <i><%= indicator.code %></i></td>
          <% end %>
        <% end %>
        <td><%= relation.y2007 %></td>
        <td><%= relation.y2008 %></td>
        <td><%= relation.y2009 %></td>
        <td><%= relation.y2010 %></td>
        <td><%= relation.y2011 %></td>
        <td><%= relation.y2012 %></td>
        <td><%= relation.y2013 %></td>
        <td><%= relation.y2014 %></td>
        <td><%= relation.y2015 %></td>
        <td><%= relation.y2016 %></td>
        <td><%= link_to 'Show', relation %></td>
        <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
        <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <% @countries.each do |country| %>
    <% if @relation.countrycode == country.code %>
      <% @indicators.each do |indicator| %>
        <% if @relation.indicatorcode == indicator.code %>
          <%= country.name %> : <%= indicator.name %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</h3>


<p>
  <strong>Codes: <%= @relation.countrycode %> - <%= @relation.indicatorcode %></strong>
</p>

<p>
  <strong>2007:</strong>
  <%= @relation.y2007 %>
</p>

<p>
  <strong>2008:</strong>
  <%= @relation.y2008 %>
</p>

<p>
  <strong>2009:</strong>
  <%= @relation.y2009 %>
</p>

<p>
  <strong>2010:</strong>
  <%= @relation.y2010 %>
</p>

<p>
  <strong>2011:</strong>
  <%= @relation.y2011 %>
</p>

<p>
  <strong>2012:</strong>
  <%= @relation.y2012 %>
</p>

<p>
  <strong>2013:</strong>
  <%= @relation.y2013 %>
</p>

<p>
  <strong>2014:</strong>
  <%= @relation.y2014 %>
</p>

<p>
  <strong>2015:</strong>
  <%= @relation.y2015 %>
</p>

<p>
  <strong>2016:</strong>
  <%= @relation.y2016 %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>