config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users
  get 'population_dynamics/home'

  get 'population_dynamics/charts'

  resources :relations
  resources :countries
  resources :indicators
  
  root 'population_dynamics#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
    validates :code, :name, presence: true
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
      @countries = if params[:term]
          Country.where("LOWER(code) LIKE ? OR LOWER(name) LIKE ?", "%#{params[:term].downcase}%", "%#{params[:term].downcase}%")
      else
          Country.all
      end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @populationtot = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.TOTL'
    @populationf = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.TOTL.FE.IN'
    @populationm = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.TOTL.MA.IN'
    @popanf = [@populationf.y2015, @populationf.y2014, @populationf.y2013, @populationf.y2012, @populationf.y2011, @populationf.y2010, @populationf.y2009, @populationf.y2008, @populationf.y2007]
    @popanm = [@populationm.y2015, @populationm.y2014, @populationm.y2013, @populationm.y2012, @populationm.y2011, @populationm.y2010, @populationm.y2009, @populationm.y2008, @populationm.y2007]
    @pop14f = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.0014.FE.IN'
    @pop1564f = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.1564.FE.IN'
    @pop65f = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.65UP.FE.IN'
    @popcompf = [@pop14f.y2015, @pop1564f.y2015, @pop65f.y2015]
    @pop14m = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.0014.MA.IN'
    @pop1564m = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.1564.MA.IN'
    @pop65m = Relation.find_by countrycode: @country.code, indicatorcode: 'SP.POP.65UP.MA.IN'
    @popcompm = [@pop14m.y2015, @pop1564m.y2015, @pop65m.y2015]
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:code, :name, :term)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :country_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :country_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<p>
  <i>Filter countries by code or name</i><br>
  <%= form_tag(countries_path, method: :get) do %>
  <%= text_field_tag :term %>
  <%= submit_tag 'Search' %>
<% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.code %></td>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @country.name %> (<%= @country.code %>)</h2>

<p>Total population: <%= @populationtot.y2015 %> (2015)</p>

<div id="chart-A" style="width:100%; height:400px;"><script></script></div>
<div class="spacer" style="height:20px;"></div>
<div id="chart-B" style="width:100%; height:400px;"><script></script></div>
<div class="spacer" style="height:20px;"></div>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

<script type="text/javascript">
$(function () { 
    $('#chart-A').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Female and male population from 2007 to 2015'
        },
        xAxis: {
            categories: ['2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007']
        },
        yAxis: {
            title: {
                text: 'Population'
            }
        },
        series: [{
            name: 'Female',
            data: <%=raw @popanf %>
        }, {
            name: 'Male',
            data: <%=raw @popanm %>
        }]
    });
    $('#chart-B').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Female and male population divided by age groups (2015)'
        },
        xAxis: {
            categories: ['0 - 14', '15 - 64', '65+']
        },
        yAxis: {
            title: {
                text: 'Population'
            }
        },
        series: [{
            name: 'Female',
            data: <%=raw @popcompf %>
        }, {
            name: 'Male',
            data: <%=raw @popcompm %>
        }]
    });
});
</script>