config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users
  get 'population_dynamics/home'

  get 'population_dynamics/charts'

  resources :relations
  resources :countries
  resources :indicators
  
  root 'population_dynamics#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indicator.rb
class Indicator < ApplicationRecord
    validates :code, :name, presence: true
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = if params[:term]
      Indicator.where('LOWER(code) LIKE ? OR LOWER(name) LIKE ?', "%#{params[:term].downcase}%", "%#{params[:term].downcase}%")
    else
      Indicator.all
    end
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:code, :name, :definition, :source, :term)
    end
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/views/indicators/_form.html.erb
<%= form_with(model: indicator, local: true) do |form| %>
  <% if indicator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indicator.errors.count, "error") %> prohibited this indicator from being saved:</h2>

      <ul>
      <% indicator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :indicator_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :indicator_name %>
  </div>

  <div class="field">
    <%= form.label :definition %>
    <%= form.text_field :definition, id: :indicator_definition %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :indicator_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/indicators/edit.html.erb
<h1>Editing Indicator</h1>

<%= render 'form', indicator: @indicator %>

<%= link_to 'Show', @indicator %> |
<%= link_to 'Back', indicators_path %>

app/views/indicators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indicators</h1>

<p>
  <i>Filter indicators by code or name</i><br>
  <%= form_tag(indicators_path, method: :get) do %>
  <%= text_field_tag :term %>
  <%= submit_tag 'Search' %>
<% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Definition</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= indicator.code %></td>
        <td><%= indicator.name %></td>
        <td><%= indicator.definition %></td>
        <td><%= indicator.source %></td>
        <td><%= link_to 'Show', indicator %></td>
        <td><%= link_to 'Edit', edit_indicator_path(indicator) %></td>
        <td><%= link_to 'Destroy', indicator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indicator', new_indicator_path %>

app/views/indicators/new.html.erb
<h1>New Indicator</h1>

<%= render 'form', indicator: @indicator %>

<%= link_to 'Back', indicators_path %>

app/views/indicators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @indicator.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @indicator.name %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @indicator.definition %>
</p>

<p>
  <strong>Source:</strong>
  <%= @indicator.source %>
</p>

<%= link_to 'Edit', edit_indicator_path(@indicator) %> |
<%= link_to 'Back', indicators_path %>